### ISSUE TITLE
CMake: Build Broken on Windows

### ISSUE THREAD

**Issue by Cringere** [pngwriter/pngwriter#115]
when I run the command `cmake ../pngwriter`  I get the error
`CMake Error at CMakeLists.txt:111 (INSTALL):
  install Library TARGETS given no DESTINATION!`
any ideas how to solve it?

**Comment by ax3l** [comment]
Can you add `-DCMAKE_INSTALL_PREFIX=<pathToInstallPNGwriterTo>`?

**Comment by Cringere** [comment]
Sorry for not clarifying, I have windows 10, my c/c++ compiler is MinGW and I downloaded pngwriter 0.6.0. adding `-DCMAKE_INSTALL_PREFIX` didn't work (i get the same error)

**Comment by ax3l** [comment]
All right, thanks for the info!

The `dev` branch now contains a fix for `CMake` to build & install the library on windows. Can you try if that works for you? In detail, [this is the CMakeLists.txt patch](https://github.com/pngwriter/pngwriter/commit/f6ef8137aa93d4885cf082142acaf4e36e7355f2) that fixed your reported issue and [here is an example script how to compile](https://github.com/pngwriter/pngwriter/blob/dev/.appveyor.yml) on windows.

Admittedly, besides the cloud service [AppVeyor](http://appveyor.com/) I have no windows machine around, so feel free to report further issues if the occur with windows - ideally as precise as possible and with debugger information if something crashes. Please just open a new GitHub issue per problem you encounter :)

Thanks again for reporting!

**Comment by Cringere** [comment]
It works perfectly now, Thank you so much for helping!
