### ISSUE TITLE
Front Page Comment

### ISSUE THREAD

**Issue by ax3l** [pngwriter/pngwriter#120]
@individual61 since the adware issue is solved since sourceforce was aquired, we should remove the rant from the README :)

https://www.reddit.com/r/sysadmin/comments/4n3e1s/the_state_of_sourceforge_since_its_acquisition_in/

I will provide a PR.

**Comment by individual61** [comment]
I had no idea, thanks for catching this.

**Comment by ax3l** [comment]
fixed :)
