### ISSUE TITLE
plot text color

### ISSUE THREAD

**Issue by leonelhs** [pngwriter/pngwriter#121]
How can I set #2b487f color for plot text? because r:17 g:28, b:50 only shows white text.

**Comment by ax3l** [comment]
thank you for the question!

Can you please post a compile-able code snippet showing your issue? PNGwriter has several overloaded interfaces for writing text and it might just lack proper documentation of the parameters in your case.

**Comment by ax3l** [comment]
Just for later a little note for us: the blue you are referring to is

| HTML | 8bit | % |
|---------|-------|-------|
| `#2b487f`|43:72:127|16.9, 28.2, 49.8|

**Comment by leonelhs** [comment]
yes thats right thats exactly was I looking for. thanks a lot.

**Comment by ax3l** [comment]
Wonderful, you are welcome! :)
