### ISSUE TITLE
No shared library in 0.7.0

### ISSUE THREAD

**Issue by rakuco** [pngwriter/pngwriter#126]
With the CMake changes that went into the 0.7.0, the `add_library()` call was changed and the build only generates a static `libPNGwriter.a` now.

Was that a deliberate change?

**Comment by ax3l** [comment]
Hi,

yes, I unified the build to standard CMake conventions that usually build one or the other, while `static` is the CMake default.

You can just pass `-DBUILD_SHARED_LIBS=ON` to your CMake call and will get shared libs. Does that work for you?

I am sorry for the hassle that this caused, I think I forgot to document that...

**Comment by rakuco** [comment]
> You can just pass -DBUILD_SHARED_LIBS=ON to your CMake call and will get shared libs. Does that work for you?

It does (the bigger context is that I package pngwriter on FreeBSD), thanks. Please feel free to close this issue, I'm leaving it open in case you want to document this change in a pull request.

**Comment by ax3l** [comment]
Hurray, thank you for packaging PNGwriter! :)

Yes, I will leave the issue open until we updated the install instructions properly.

**Comment by ax3l** [comment]
documented with #127 :)
