### ISSUE TITLE
Malformed make build files upon cmake (empty macro flags)

### ISSUE THREAD

**Issue by plammens** [pngwriter/pngwriter#136]
On Windows (with `cygwin64`), when `cmake` generates the configuration files for `pngwriter` some of the "define" macros are empty (as in `CXX_DEFINES = -D-DSOME_MACRO`); thus when running `make install`, installation halts with the following error.

```text
<command-line>:0:1: error: macro names must be identifiers
```

Versions:
- `cmake` 3.6.2
- GNU `make` 4.2.1
- `cygwin64` 3.0.5

# Steps to reproduce

1. Clone the git repo
2. Make a build directory and run `cmake` on `pngwriter`:
```bash
cd pngwriter
mkdir -p build-install
cd build-install
cmake ../ -DCMAKE_INSTALL_PREFIX=$HOME/libs/
```
3. `make install`

**Expected result**:  `pngwriter` builds and installs correctly
**Actual result**:  the build stops immediately with the error `<command-line>:0:1: error: macro names must be identifiers`

# Manual solution

I have found the following manual solution to this problem. In the build directory in which `cmake` was executed, under `CMakeFiles`, there are several directories ending with `.dir` (one for each source directory in the project root), generated by `cmake`. In each of these directories, there is a file named `flags.make`, which contains the compiler flags that will be used to build the source:

```make
# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.6

# compile CXX with /usr/bin/c++.exe
CXX_FLAGS = -O3 -DNDEBUG  

CXX_DEFINES = -D-DPNG_STATIC -DNO_FREETYPE

CXX_INCLUDES = -I/home/Paolo/libs/pngwriter/build-install/src -I/home/Paolo/libs/pngwriter/src 
```

As you can see, the `CXX_DEFINES` variable contains a malformed define flag with an empty macro name: `-D[-D...]`. Remove the first `-D` (despite the `DO NOT EDIT!` imperative at the top of the file :wink:). E.g., the line should go from something like
```make
CXX_DEFINES = -D-DPNG_STATIC -DNO_FREETYPE
```
to something like
```make
CXX_DEFINES = -DPNG_STATIC -DNO_FREETYPE
```
(the exact line depends on the configuration options, such as having `FreeType` enabled or not).

If you do this for every directory ending in `.dir` (`blackwhite.dir`, `diamond.dir`, `lyapunov.dir`,  `pngtest.dir`, `PNGwriter.dir`, `readwrite.dir`), and you run `make install` again (from the build directory), it seems to work &mdash; I was able to use the library successfully afterwards.

## Script (for the lazy)

A quick throwaway Python3 script for fixing the problem can be found [here](https://gist.github.com/plammens/dcd6d4b4a8c3a0f0d49318dead520fbe).

### Usage

After you've done `cmake`, in that same directory, save the script in a file, e.g. `fix.py`. Run `python3 fix.py`. Try running `make install` again.

**Comment by ax3l** [comment]
Thank you for the report!
Hm, that looks malformed indeed. Can you post the output of your `cmake ../` command?

Could be transitively be added from libpng or zlib... How did you install those two?

**Comment by plammens** [comment]
@ax3l Here is the output of `cmake ../ -DCMAKE_INSTALL_PREFIX=$HOME/libs/`:
```text
-- The CXX compiler identification is GNU 7.4.0
-- Check for working CXX compiler: /usr/bin/c++.exe
-- Check for working CXX compiler: /usr/bin/c++.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found ZLIB: /usr/lib/libz.dll.a (found version "1.2.11")
-- Found PNG: /usr/lib/libpng.dll.a (found suitable version "1.6.34", minimum required is "1.2.9")
-- Could NOT find Freetype (missing:  FREETYPE_LIBRARY FREETYPE_INCLUDE_DIRS)

PNGwriter build configuration:
  PNGwriter Version: 0.7.0
  C++ Compiler : GNU 7.4.0
    /usr/bin/c++.exe

  Installation prefix: /home/Paolo/libs

  Build Type: Release
  Build Options:
    FREETYPE: OFF

-- Configuring done
-- Generating done
-- Build files have been written to: /home/Paolo/libs/pngwriter/build-install
```

I installed `zlib` and `libpng` through `cygwin`'s package installer.

I also tried with `-DPNGwriter_USE_FREETYPE=OFF`, with the same results.

**Comment by ax3l** [comment]
Thank you for the info!
I am having a hard time (without a windows PC) to reproduce this in #137.
Currently, our CI assumes and tests a VisualStudio build.

How did you install zlib and libpng with cygwin? What exact package names/line did you use for `setup-x86_64.exe`?
Update: ok, I can reproduce it now on AppVeyor (remotely...)

**Comment by ax3l** [comment]
Hm, this looks like a CMake bug in `FindPNG.cmake` to me:
https://github.com/Kitware/CMake/blob/v3.6.2/Modules/FindPNG.cmake#L114-L121
Line 144 should only read
```cmake
 set (PNG_DEFINITIONS PNG_STATIC)
```

You can work-around this by compiling `PNGwriter` with `-DBUILD_SHARED_LIBS=ON`:
```bash
cmake ../ -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX=$HOME/libs/
```

**Comment by ax3l** [comment]
I opened an upstream merge request to CMake: https://gitlab.kitware.com/cmake/cmake/merge_requests/3337
This will take some time until it trickles down to the Cygwin CMake package, so you might want to use your work-around or build shared libs as in my work-around in the meantime :) 

CMake 3.15.0+ will ship the fix.

**Comment by plammens** [comment]
@ax3l Wow, that was quick! 😄 Thanks for the response!

**Comment by ax3l** [comment]
You are welcome :)
Thank you again for the helpful, detailed report!
