### ISSUE TITLE
undefined reference to symbol 

### ISSUE THREAD

**Issue by johughes99** [pngwriter/pngwriter#139]
When linking pngwriter to my code I get the following error

/usr/bin/ld: /usr/local/lib/libPNGwriter.a(pngwriter.cc.o): undefined reference to symbol 'png_set_sig_bytes@@PNG16_0'
//usr/lib/x86_64-linux-gnu/libpng16.so.16: error adding symbols: DSO missing from command line

I'm using Ubuntu 18.04 and I have libpng installed  (libpng-dev)

**Comment by johughes99** [comment]
Solved it. I add in -lpng - AFTER the libPNGwriter.a - although the manual tells you to have it before.

**Comment by ax3l** [comment]
Hi @johughes99,

oh dang, that's definitely wrong in the docs. Linking static libraries is order-dependent. Fixed in #140, thank you for the report!

**Comment by ax3l** [comment]
Fixed in #140
