### ISSUE TITLE
Resize image without losing all contents

### ISSUE THREAD

**Issue by RajaSrinivasan** [pngwriter/pngwriter#142]
I am creating an image and filling lines of text. Dont know how many lines when i start. So I would like to truncate the image once i know how many lines i wrote.

is there a way to do this?

thanks

**Comment by ax3l** [comment]
Hi,

that's not possible with the current implementation.
This would probably also be relatively slow, as one has to seek and copy over the data on every resize.

Would it be possible for you to store your data in some kind of container that supports fast resizes and then write all data at once?

**Comment by RajaSrinivasan** [comment]
That is what i ended up doing. Thanks, srini
