### ISSUE TITLE
VCPKG installed the VS2019 Debug library into the release area of VCPKG and the Release library into the Debug area. 

### ISSUE THREAD

**Issue by ndl303** [pngwriter/pngwriter#143]
Thanks for building pngwriter. 

I'm not sure if this is a pngwriter cmake issue or a VCPKG issue but I installed pngwriter into VCPKG ( `.\vcpkg install pngwriter`). When I used the library in a Debug build in VS2019 it compiled cleanly but failed during link, claiming incompatibility as the main code was built with MDd_DynamicDebug while the pngwriter lib  was built with MD_DynamicRelease. 

```
Build started...
1>------ Build started: Project: test_png, Configuration: Debug x64 ------
1>PNGwriter.lib(pngwriter.cc.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '2' doesn't match value '0' in test_png.obj
1>PNGwriter.lib(pngwriter.cc.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MD_DynamicRelease' in test_png.obj
1>LINK : warning LNK4098: defaultlib 'MSVCRTD' conflicts with use of other libs; use /NODEFAULTLIB:library
1>PNGwriter.lib(pngwriter.cc.obj) : error LNK2001: unresolved external symbol __imp__invalid_parameter
1>PNGwriter.lib(pngwriter.cc.obj) : error LNK2001: unresolved external symbol __imp__CrtDbgReport
1>C:\argdev\ndl303\ARG_Instruments\IFTS\ifts_thermal_module_firmware\CompilerIDE\VS2019\x64\Debug\test_png.exe : fatal error LNK1120: 2 unresolved externals
1>Done building project "test_png.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

```

I verified the linker was loading the debug version from the debug folder using linker option **\VERBOSE:lib**,

```
1>    Searching C:\argdev\ndl303\ARG_ThirdParty\vcpkg\installed\x64-windows-static-md\debug\lib\lzmad.lib:
1>    Searching C:\argdev\ndl303\ARG_ThirdParty\vcpkg\installed\x64-windows-static-md\debug\lib\netcdf.lib:
1>    Searching C:\argdev\ndl303\ARG_ThirdParty\vcpkg\installed\x64-windows-static-md\debug\lib\PNGwriter.lib:
1>PNGwriter.lib(pngwriter.cc.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '2' doesn't match value '0' in test_png.obj
1>PNGwriter.lib(pngwriter.cc.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MDd_DynamicDebug' doesn't match value 'MD_DynamicRelease' in test_png.obj
1>    Searching C:\argdev\ndl303\ARG_ThirdParty\vcpkg\installed\x64-windows-static-md\debug\lib\python310_d.lib:
```

I tracked the problem down and the release build during vcpkg installation had been placed into the debug folder and vice versa.  I was suspicious when I noted that the so-called debug library was noticeably smaller than the release version.  Swapping the two libraries around fixed the problem.  

I use a non-standard triplet for vcpkg , **x64-windows-static-md**, but apart from that it is a very plain installation of vcpkg.

I include  the short program I wrote in VS2019, noting that this is CMAKE installation/ linking issue and not a source code issue.

```
  #include <pngwriter.h>
  
  void main()
  {
	  std::string filename("C:\\dev\\my_test_image.png");
	  pngwriter image;
	  
	  image.readfromfile(filename.c_str());
	  printf("Done\n");
}
```

Thanks
Nick Lloyd

**Comment by ndl303** [comment]
Sorry. My mistake. I'm not sure how it happened but the normal Visual Studio compiler settings I use for Debug compiling were using Release settings. I apologize.

**Comment by ax3l** [comment]
No worries and thanks for the report nonetheless!

Let us know if you encounter any other issues. Have fun with PNGwriter!
