### ISSUE TITLE
Move Owner Ship to pngwriter Org

### ISSUE THREAD

**Issue by ax3l** [pngwriter/pngwriter#34]
- [x] move to organization: https://github.com/pngwriter
- [x] update all links to use new github link #41
- [x] add a nice catchy image to the organization

**Comment by ax3l** [comment]
@individual61 do you have a catchy logo for pngwriter?

**Comment by individual61** [comment]
Wow, yes in fact. I found the original Gimp file from August 2002. An online converter just flattened the layers. I'll have to download GIMP tonight to export it manually. Do you know if there is a target size?

PS: Perhaps all of the above is rendered moot by your use of 'catchy'. Are you suggesting we need a new logo? =)

**Comment by ax3l** [comment]
Haha :)

2002 sounds exciting - can you send me the gimp file ? :) let's upload a preview here so we know if we should "modernize" it or if it is already "retro" :D

**Comment by individual61** [comment]
Ok, tonight.

**Comment by individual61** [comment]
![logo1](https://cloud.githubusercontent.com/assets/7351001/6408950/83396de8-be11-11e4-9823-f8e723c936b9.png)

**Comment by individual61** [comment]
I think it's fine, just needs some antialiasing.

**Comment by ax3l** [comment]
ah ok I remember that one :)
for the github organization logo we rather need a squared image I guess.

**Comment by individual61** [comment]
Ok, let's see what I can do.

**Comment by individual61** [comment]
How about this?
![pngwriter logo square](https://cloud.githubusercontent.com/assets/7351001/6633547/a615647e-c907-11e4-8853-64f682656585.png)

**Comment by individual61** [comment]
I like this one better.
![pngwriter logo square rev b](https://cloud.githubusercontent.com/assets/7351001/6633634/b6e96fc4-c908-11e4-9437-e5a00657613f.png)

**Comment by ax3l** [comment]
second one is sexy, I take it :)

**Comment by ax3l** [comment]
updated and closed.

thank you! :+1:
