### ISSUE TITLE
cannot plot text

### ISSUE THREAD

**Issue by syswow** [pngwriter/pngwriter#48]
Hi,
I write the short test, it only generates a full black png.

```
int main()
{
   pngwriter one(300,300,0,"mytest.png");   
   std::cout << "Generating mytest.png...";
   one.plot_text("Ubuntu-M.ttf", 16, 30, 30,0, "Hello World", 255,255,255);
   one.write_png();
   return 0;
}
```

**Comment by syswow** [comment]
Fixed

**Comment by ax3l** [comment]
hi @syswow  - thanks for the report!

did the latest version of our release branch `release-0.5.5` solve your problem? Did you find it in `0.5.4`?

**Comment by syswow** [comment]
@ax3l  It's my fault, because, I use the wrong text postion. 
pngwriter works very well! :smile:  :+1:

**Comment by syswow** [comment]
I am very glad to see the new version have come.

**Comment by ax3l** [comment]
cool, all right :+1:
