### ISSUE TITLE
Version in pngwriter.h

### ISSUE THREAD

**Issue by ax3l** [pngwriter/pngwriter#49]
Is writing `0.55` for `0.5.5` a good idea or should we define `major`, `minor` and `revision` in individual defines?

can we deprecate and in `0.6.0` remove the [old define](https://github.com/pngwriter/pngwriter/blob/d87668cf7294a086ec8b405f2db2d228ceed7274/src/pngwriter.h#L46) `PNGWRITER_VERSION`?

**Comment by individual61** [comment]
Hmm. Is it a bad idea to stick with the current scheme?

If we remove the version method, as you suggest for 0.6.0, what will take its place?

**Comment by ax3l** [comment]
The problem is, that minor and revision numbers can not be distinguished and two-digit numbers would also fail.

I will provide the old scheme as "deprecated" via a define in case someone uses it. I will show you in a pull request :)

**Comment by individual61** [comment]
Perfect, thanks!

**Comment by ax3l** [comment]
implemented and proposed in #50 -> feel free to take a look :)

**Comment by individual61** [comment]
Looks good to me!

**Comment by ax3l** [comment]
okili dokili, feel free to hit the powerful "merge button".
