### ISSUE TITLE
Creation Time Wrong?

### ISSUE THREAD

**Issue by ax3l** [pngwriter/pngwriter#76]
The creation time looks odd (png meta).

```bash
# ImageMagick
identify -verbose image.png
# [...]
  Properties:
    Author: Is OK!
    Creation Time: 10 Dec
    date:create: 2015-12-10T18:16:57+01:00
    date:modify: 2015-12-10T18:16:57+01:00
    Description: Is OK, too!
# [...]
```

[Location 1](https://github.com/pngwriter/pngwriter/blob/55825e8b7758a34506a8b947e6648b20b02bf9f0/src/pngwriter.cc#L995-L1011), [location 2](https://github.com/pngwriter/pngwriter/blob/55825e8b7758a34506a8b947e6648b20b02bf9f0/src/pngwriter.cc#L1051-L1092)

Maybe we need to crop the user input/author to strlen 28 ? but description can be longer... hm.
what is the actual length of `png_text::text`?

**Comment by individual61** [comment]
What's odd about it?

**Comment by ax3l** [comment]
The creation time is only "10 Dec" and not a timestamp as below o.O

**Comment by individual61** [comment]
Oops, yeah.

**Comment by ax3l** [comment]
oh, could also be related to an other change I made in app testing that. need to investigate further, might be wrong.

**Comment by ax3l** [comment]
ok, it's a problem in PNGwriter.
the size [here](https://github.com/pngwriter/pngwriter/blob/55825e8b7758a34506a8b947e6648b20b02bf9f0/src/pngwriter.cc#L1078) can be too short and [this](https://github.com/pngwriter/pngwriter/blob/55825e8b7758a34506a8b947e6648b20b02bf9f0/src/pngwriter.cc#L1084) is also looking for the size of an undefined var...
