### ISSUE TITLE
8 Bit Reads: Upper Bound Broken of Scale-Up to 16-bit

### ISSUE THREAD

**Issue by mxmlnkn** [pngwriter/pngwriter#89]
As `0.996109 ~ 1-1/255` this seems to happen because of some error in upscaling 255 to 65535. So unlike mentioned in the documentation 

>  returned value will be of type int and be between 0 and 65535.

the highest value is not `65535` but `65280=65535-255`.
This bug afflicts both `read` and `dread` and all other read functions which call `read`, like scaling and interpolation, ....
I will submit a pull request shortly.

**Comment by mxmlnkn** [comment]
... I'm not entirely sure how to do this though.
The problem are all lines (these are really many!) which include `*256`. Correctly this should be `/255.0*65535.0` for some fun reason this is exactly the same as `*257`, but the latter is a somewhat magic number, I wouldn't want to write this without a lengthy comment. I guess the best way is a global define `#define scale8to16bit 257 // actually /255.0*65535.0, but that is exactly 257, so no floating point arithmetic is needed here`

**Comment by ax3l** [comment]
> I guess the best way is a global define #define scale8to16bit 257 // actually /255.0*65535.0, but that is exactly 257, so no floating point arithmetic is needed here

yes, too many magic numbers all over the place (https://github.com/pngwriter/pngwriter/issues/12#issuecomment-40074636).

**Comment by ax3l** [comment]
Same bug as #13 but only for 8bit images?

**Comment by mxmlnkn** [comment]
Yes, very similar. b3c0ef95da01a8d5aafd438186f57756a0eb87d3 seems to correct a similar array in the `plot` function, so the other way around. And it solves the `dread` problem by introducing a differentiation between 8 and 16-bit.

I find it interesting to see the `257` in the old code for `plot` ...

It also seems `blackwhite.cc` is exactly such an example you wanted in the PR, but yeah, it only seems to do this for one bit depth, not both.
